from cruzamento import Cruzamento
from gpiozero import Button

class Sensores():
    def __init__(self, SENSOR_PASSAGEM_1, SENSOR_VELOCIDADE_1_A,
                SENSOR_VELOCIDADE_1_B, SENSOR_PASSAGEM_2,
                SENSOR_VELOCIDADE_2_A, SENSOR_VELOCIDADE_2_B):

        self.SENSOR_PASSAGEM_1 = SENSOR_PASSAGEM_1
        self.SENSOR_PASSAGEM_2 = SENSOR_PASSAGEM_2

        self.SENSOR_VELOCIDADE_1_A = SENSOR_VELOCIDADE_1_A
        self.SENSOR_VELOCIDADE_1_B = SENSOR_VELOCIDADE_1_B

        self.SENSOR_VELOCIDADE_2_A = SENSOR_VELOCIDADE_2_A
        self.SENSOR_VELOCIDADE_2_B = SENSOR_VELOCIDADE_2_B